version: "3.8"

services:
  backend:
    image: tien2k3/shoeshop-backend:latest   
    ports:
      - "5000:5000"
    networks:
      - shoeshop-network
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://shoeshop_mongo:27017/shoeshop
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  frontend:
    image: tien2k3/shoeshop-frontend:latest  
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - shoeshop-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    networks:
      - shoeshop-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

networks:
  shoeshop-network:
    driver: overlay   

volumes:
  mongo-data:
    driver: local
