version: "3.8"
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    networks:
      - shoeshop-network
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/shoeshop

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - shoeshop-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - shoeshop-network

networks:
  shoeshop-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
